name: Export my notion workspace

on:
  schedule:
    - cron: "0 */24 * * *"  # Call the export every 6 hours
  workflow_dispatch: {}

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: AsahiMoon/notion-backup@v1.0.0
        with:
          pages: "5dc844e87e4647bcbbe1a65a4cbe4bea"  # Pages IDs identified in (step 2)  
          output-dir: notion-backup
          notion-token: ${{ secrets.NOTION_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          notion-file-token: ${{ secrets.NOTION_FILE_TOKEN }}
